# Generated by Django 5.2 on 2025-04-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser_and_calculator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
