# Generated by Django 5.2 on 2025-04-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser_and_calculator", "0002_alter_product_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="add_margin",
            field=models.BooleanField(default=False, verbose_name="Начислять 20%"),
        ),
        migrations.AddField(
            model_name="product",
            name="final_price",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="Полная цена"
            ),
        ),
    ]
