# Generated by Django 5.2 on 2025-04-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser_and_calculator", "0003_product_add_margin_product_final_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="add_margin",
            field=models.BooleanField(default=False, verbose_name="20%"),
        ),
        migrations.AlterField(
            model_name="product",
            name="final_price",
            field=models.FloatField(
                blank=True, editable=False, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(blank=True, null=True, verbose_name="Цена +20%"),
        ),
    ]
