name: Deploy Django App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_PROJECT_PATH }}/builder_parser
            sudo systemctl stop gunicorn
            git reset --hard HEAD
            git pull https://github.com/bravexistence/django_calculator_for_building_materials.git main
            export PATH="$HOME/.local/bin:$PATH"
            poetry config virtualenvs.in-project true
            poetry install --no-root
            poetry run python manage.py migrate
            poetry run python manage.py collectstatic --noinput
            sudo systemctl daemon-reload
            sudo systemctl start gunicorn
            sudo systemctl status gunicorn || exit 1
