name: Deploy Django App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            pwd
            ls -la
            echo "=== git remote -v ==="
            git remote -v || echo "NO GIT REMOTE"
            echo "=== git branch ==="
            git branch || echo "NO BRANCH"
            echo "=== git status ==="
            git status || echo "NO STATUS"
            echo "=== git config --list ==="
            git config --list || echo "NO CONFIG"
            echo "=== check .git/config ==="
            cat .git/config || echo "NO .git/config FILE"
            echo "=== check ssh to github ==="
            ssh -T git@github.com || echo "SSH to github FAILED"
